Add project setup
BIBSYSDEV/nva-doi-partner-data pull request #1
Opened 2020-09-30 22:36 UTC by brinxmat

2020-09-30 22:39 UTC, brinxmat commented on build.gradle
> +                excludes = ['**datacite**']
To ignore generated classes

2020-09-30 22:39 UTC, brinxmat commented on build.gradle
> +                excludes = ['**datacite**']
To ignore generated classess

2020-09-30 22:39 UTC, brinxmat commented on config/pmd/ruleset.xml
> +  <exclude-pattern>.*/datacite-data/.*</exclude-pattern>
We don't want PMD to look at generated datacite classes

2020-10-01 11:57 UTC, axthosarouris commented on build.gradle
> +allprojects {
I am not sure if you need to add the following element. Probably not :)
```
plugins {
    id 'java'
    id 'jacoco'
    id 'checkstyle'
    id 'pmd'
    id "nebula.lint" version "16.9.0"

}
```

2020-10-01 12:01 UTC, axthosarouris approved these changes

2020-10-01 12:01 UTC, axthosarouris commented on build.gradle
> +
maybe add the compatibility claims, just to be sure that we are always referring to the correct version

```

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11
```

2020-10-01 12:01 UTC, axthosarouris commented on config/checkstyle/checkstyle.xml
> +      <property name="tokens" value="METHOD_DEF, CTOR_DEF, ANNOTATION_FIELD_DEF"/>
remove CTOR_DEF from here. We do not need to add Javadoc to all constructors.

2020-10-01 12:01 UTC, axthosarouris commented on config/checkstyle/checkstyle.xml
> +      <property name="allowedAnnotations" value="Override, Test"/>
Add ParametrizedTest to avoid having to add Javadoc to all ParameterizedTests

2020-10-01 12:09 UTC, axthosarouris requested changes
This is the only requested change. The previous are comments: travis is missing

2020-10-09 09:47 UTC, axthosarouris approved these changes

2020-10-09 09:52 UTC, merged