Renamed to DataCiteMetadataDto
BIBSYSDEV/nva-doi-partner-data pull request #6
Opened 2020-11-19 13:50 UTC by janbj

2020-11-19 14:03 UTC, norrs requested changes

2020-11-19 14:03 UTC, norrs commented on datacite-transform/src/main/java/no/unit/nva/transformer/Transformer.java
> +        dataCiteMes(dataCiteMetadataDto);
dataCiteMes?

2020-11-20 07:50 UTC, janbj commented on datacite-transform/src/main/java/no/unit/nva/transformer/Transformer.java
> +        dataCiteMes(dataCiteMetadataDto);
Hm

2020-11-20 08:17 UTC, norrs requested changes

2020-11-20 08:17 UTC, norrs commented on datacite-transform/src/main/java/no/unit/nva/transformer/Transformer.java
> +     * @param dataCiteMetadataDto A DynamoDB record.
DynamoDB probably should be replaced with DataCiteMetadataDto to hide storage impl.

2020-11-20 08:17 UTC, norrs commented on datacite-transform/src/main/java/no/unit/nva/transformer/Transformer.java
> +     * @param dataCiteMetadataDto A DynamoDB record.
So ensure the javadoc is correct.

2020-11-20 14:48 UTC, brinxmat approved these changes

2020-11-23 09:48 UTC, norrs approved these changes

2020-11-23 09:49 UTC, norrs commented
Since @janbj is AFK this week(?), I'm merging this for him @brinxmat

2020-11-23 09:49 UTC, merged